# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --no-cache-dir .

# Copy application source
COPY . .

# Default command to start the MCP server on STDIO
CMD ["mcp", "run", "main.py"]
